### ISSUE TITLE
Support to reference shared and dedicated volumes in terraform plugin

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#562]
This is related to issue #561.

We are looking to define a manager instance that has BOTH a shared volume (shared with all other managers) and a dedicated volume. How should the volumes be defined and then referenced in the instance definition? Should the volumes be defined in separate files and then referenced (via something like an `Attachment`) in a flavor plugin?

Any direction would be appreciated!

**Comment by chungers** [comment]
I personally think `Attachment` in the SPI still needs better definition and work -- in particular because it reaches outside the boundaries of a group.   So for now, I am inclined to exploit existing primitives to support these requirements as a short-term approach.

What I mean here is that for dedicated volumes -- at least with the terraform plugin -- we can allow the resource definition to be a part of the resource spec for the instance.  Using the `scope` field, we should be able to designate lifecycle-specific handling of these resources.

Now a globally shared resource is a little harder, because it doesn't make a lot of sense to have its declaration as a part of the instances and their resources (@dedicated or @default)...  Ideally it's best of have a completely separate terraform plugin configuration, as a stand-alone instance plugin, for provisioning just that resource.  To illustrate my point, consider the example below.  Note that there are two sections -- one for the group and one for an instance which just provisions globally referenced resources.

```
- Plugin: instance-terraform-global-resources # made up name
   Properties:
           # Here we have the specs for the global resources
- Plugin: group
  Properties:
    ID: {{ $groupName }}
    Properties:
      Allocation:
        Size: {{ $size }}
      Flavor:
        Plugin: flavor-vanilla
        Properties:
          Init:
            - apt-get update -y
            - apt-get install wget curl
            - wget -qO- https://get.docker.com | sh
          Tags:
            project: {{ $project }}
      Instance:
        Plugin: instance-terraform
        Properties:
           # Here we have the specs for the instance and its dedicated / default volumes
```
The spec here makes more sense as global resources are separate from instance dedicated/ default resources.   However, this means that we need to support mixed typed plugin configurations in the array, because up until now, the entire input is assumed to be an array of `Group` specs.   There are already plans to support this and introduce dependency ordering so that we can provision the global, required resources before we start with the group instances.

What do you think?  Does this seem reasonable to you?
