### ISSUE TITLE
Can not start Vagrant instance with Swarm

### ISSUE THREAD

**Issue by scornelissen85** [docker/infrakit#603]
I have created an playbook with a Vagrant instance and with Swarm flavor. When I start this combi then there will be no Vagrant instance started up. When I changed the flavor Swarm to Vanilla then Vagrant VM's start up.

I'm using the playbook linuxkit and changed that to support Vagrant and Swarm. I'm using Vagrant version 1.9.4. I'm running on Ubuntu 17.04.

This is my yml which failed:
```
{{/* Input to create a group using the vagrant instance plugin and manager */}}
{{/* =% managerCommit true false %= */}}


{{ $groupName := flag "group-name" "string" "Name of group" | prompt "Name of the group?" "string" "mygroup" }}

{{ $project := var "/project" | flag "project" "string" "Project name" | prompt "Project?" "string" "myproject" }}

{{ $box := flag "box" "string" "Vagrant Box" | prompt "Which box do you want to use?" "string" "summercamp-centos7-1" }}
{{ $cpus := flag "cpus" "int" "CPUs" | prompt "How many CPUs?" "int" 1 }}
{{ $memory := flag "memory" "int" "Memory in MB" | prompt "How many mb for memory?" "int" 1024 }}

- Plugin: group
  Properties:
    ID: {{ $groupName }}
    Properties:
      Allocation:
        LogicalIDs:
          - 192.168.2.200
          - 192.168.2.201
          - 192.168.2.202
      Flavor:
        Plugin: 'flavor-swarm/manager'
        Properties:
          SwarmJoinIP: '192.168.2.200'
          Docker:
            Host: 'tcp://182.168.2.200:4243'
      Instance:
        Plugin: instance-vagrant
        Properties:
          Box: {{ $box }}
          CPUs: {{ $cpus }}
          Memory: {{ $memory }}
```
This is the logging of instance-vagrant:
```
time="2017-06-21T23:46:32+02:00" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 86\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Handshake.Implements\",\"params\":{},\"id\":1916479468091639875}" 
time="2017-06-21T23:46:32+02:00" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"result\":{\"APIs\":[{\"Name\":\"Instance\",\"Version\":\"0.6.0\"},{\"Name\":\"Metadata\",\"Version\":\"0.1.0\"}]},\"id\":1916479468091639875}\n" 
time="2017-06-21T23:46:32+02:00" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 81\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Handshake.Types\",\"params\":{},\"id\":2685861875438085394}" 
time="2017-06-21T23:46:32+02:00" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"result\":{\"Types\":{\"Instance/0.6.0\":[\".\"],\"Metadata/0.1.0\":[\".\"]}},\"id\":2685861875438085394}\n" 
time="2017-06-21T23:46:32+02:00" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 81\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Handshake.Types\",\"params\":{},\"id\":5598247749244552669}" 
time="2017-06-21T23:46:32+02:00" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"result\":{\"Types\":{\"Instance/0.6.0\":[\".\"],\"Metadata/0.1.0\":[\".\"]}},\"id\":5598247749244552669}\n" 
time="2017-06-21T23:46:37+02:00" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 86\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Handshake.Implements\",\"params\":{},\"id\":3179370318160187396}" 
time="2017-06-21T23:46:37+02:00" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"result\":{\"APIs\":[{\"Name\":\"Instance\",\"Version\":\"0.6.0\"},{\"Name\":\"Metadata\",\"Version\":\"0.1.0\"}]},\"id\":3179370318160187396}\n" 
time="2017-06-21T23:46:37+02:00" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 80\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Handshake.Types\",\"params\":{},\"id\":450928423094278022}" 
time="2017-06-21T23:46:37+02:00" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"result\":{\"Types\":{\"Instance/0.6.0\":[\".\"],\"Metadata/0.1.0\":[\".\"]}},\"id\":450928423094278022}\n" 
time="2017-06-21T23:46:39+02:00" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 86\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Handshake.Implements\",\"params\":{},\"id\":6482714399587535429}" 
time="2017-06-21T23:46:39+02:00" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"result\":{\"APIs\":[{\"Name\":\"Instance\",\"Version\":\"0.6.0\"},{\"Name\":\"Metadata\",\"Version\":\"0.1.0\"}]},\"id\":6482714399587535429}\n" 
time="2017-06-21T23:46:39+02:00" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 159\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Instance.Validate\",\"params\":{\"Type\":\"\",\"Properties\":{\"Box\":\"summercamp-centos7-1\",\"CPUs\":1,\"Memory\":1024}},\"id\":9146385952407968874}" 
time="2017-06-21T23:46:39+02:00" level=info msg="Vagrant STDOUT: validate, return nil" 
```
And this from group-stateless:
```
time="2017-06-21T21:48:49Z" level=info msg="Logical ID 192.168.2.200 is missing, provisioning new instance" 
time="2017-06-21T21:48:49Z" level=info msg="Logical ID 192.168.2.201 is missing, provisioning new instance" 
time="2017-06-21T21:48:49Z" level=info msg="Logical ID 192.168.2.202 is missing, provisioning new instance" 
time="2017-06-21T21:48:50Z" level=error msg="Failed to Prepare instance: Post http://h: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-06-21T21:48:50Z" level=error msg="Failed to Prepare instance: Post http://h: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-06-21T21:48:50Z" level=error msg="Failed to Prepare instance: Post http://h: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
```
This is the logging of flavor-swarm:
```
time="2017-06-21T21:50:31Z" level=debug msg="manager >>> context.retries = 0 err= template: file://localhost//:32:31: executing \"file://localhost//\" at <SWARM_JOIN_TOKENS>: error calling SWARM_JOIN_TOKENS: cannot prepare: no swarm status i= 0" 
time="2017-06-21T21:50:31Z" level=warning msg="Retries exceeded and error: template: file://localhost//:32:31: executing \"file://localhost//\" at <SWARM_JOIN_TOKENS>: error calling SWARM_JOIN_TOKENS: cannot prepare: no swarm status" 
time="2017-06-21T21:50:31Z" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32000,\"message\":\"template: file://localhost//:32:31: executing \\\"file://localhost//\\\" at \\u003cSWARM_JOIN_TOKENS\\u003e: error calling SWARM_JOIN_TOKENS: cannot prepare: no swarm status\",\"data\":null},\"id\":7151024262844221673}\n" 
time="2017-06-21T21:50:31Z" level=debug msg="manager >>> context.retries = 0 err= template: file://localhost//:32:31: executing \"file://localhost//\" at <SWARM_JOIN_TOKENS>: error calling SWARM_JOIN_TOKENS: cannot prepare: no swarm status i= 0" 
time="2017-06-21T21:50:31Z" level=warning msg="Retries exceeded and error: template: file://localhost//:32:31: executing \"file://localhost//\" at <SWARM_JOIN_TOKENS>: error calling SWARM_JOIN_TOKENS: cannot prepare: no swarm status" 
time="2017-06-21T21:50:31Z" level=debug msg="Sending response HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\n\r\n{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32000,\"message\":\"template: file://localhost//:32:31: executing \\\"file://localhost//\\\" at \\u003cSWARM_JOIN_TOKENS\\u003e: error calling SWARM_JOIN_TOKENS: cannot prepare: no swarm status\",\"data\":null},\"id\":2463185825594672965}\n" 
time="2017-06-21T21:50:39Z" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 540\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Flavor.Prepare\",\"params\":{\"Type\":\"manager\",\"Properties\":{\"Docker\":{\"Host\":\"tcp://182.168.2.200:4243\"},\"SwarmJoinIP\":\"192.168.2.200\"},\"Spec\":{\"Properties\":{\"Box\":\"summercamp-centos7-1\",\"CPUs\":1,\"Memory\":1024},\"Tags\":{\"infrakit.config_sha\":\"rcfamsgvh2l3sovtwrxdla7ktysvnf3p\",\"infrakit.group\":\"mygroup\"},\"Init\":\"\",\"LogicalID\":\"192.168.2.200\",\"Attachments\":null},\"Allocation\":{\"Size\":0,\"LogicalIDs\":[\"192.168.2.200\",\"192.168.2.201\",\"192.168.2.202\"]},\"Index\":{\"Group\":\"mygroup\",\"Sequence\":3}},\"id\":3133205110039675671}" 
time="2017-06-21T21:50:39Z" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 540\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Flavor.Prepare\",\"params\":{\"Type\":\"manager\",\"Properties\":{\"Docker\":{\"Host\":\"tcp://182.168.2.200:4243\"},\"SwarmJoinIP\":\"192.168.2.200\"},\"Spec\":{\"Properties\":{\"Box\":\"summercamp-centos7-1\",\"CPUs\":1,\"Memory\":1024},\"Tags\":{\"infrakit.config_sha\":\"rcfamsgvh2l3sovtwrxdla7ktysvnf3p\",\"infrakit.group\":\"mygroup\"},\"Init\":\"\",\"LogicalID\":\"192.168.2.202\",\"Attachments\":null},\"Allocation\":{\"Size\":0,\"LogicalIDs\":[\"192.168.2.200\",\"192.168.2.201\",\"192.168.2.202\"]},\"Index\":{\"Group\":\"mygroup\",\"Sequence\":3}},\"id\":3603928780590567392}" 
time="2017-06-21T21:50:39Z" level=debug msg="Received request POST / HTTP/1.1\r\nHost: h\r\nAccept-Encoding: gzip\r\nContent-Length: 540\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"Flavor.Prepare\",\"params\":{\"Type\":\"manager\",\"Properties\":{\"Docker\":{\"Host\":\"tcp://182.168.2.200:4243\"},\"SwarmJoinIP\":\"192.168.2.200\"},\"Spec\":{\"Properties\":{\"Box\":\"summercamp-centos7-1\",\"CPUs\":1,\"Memory\":1024},\"Tags\":{\"infrakit.config_sha\":\"rcfamsgvh2l3sovtwrxdla7ktysvnf3p\",\"infrakit.group\":\"mygroup\"},\"Init\":\"\",\"LogicalID\":\"192.168.2.201\",\"Attachments\":null},\"Allocation\":{\"Size\":0,\"LogicalIDs\":[\"192.168.2.200\",\"192.168.2.201\",\"192.168.2.202\"]},\"Index\":{\"Group\":\"mygroup\",\"Sequence\":3}},\"id\":1495522759525969578}" 
```
When I check ```vagrant global-status```, I don't see any new VMs starting up; while with flavor-vanilla it is starting.
