### ISSUE TITLE
infrakit group commit failing to parse yaml file

### ISSUE THREAD

**Issue by OverlyExcessive** [docker/infrakit#674]
Translating the `cattle.json` to YAML (see below) and running `infrakit group commit ...` is producing a parsing error:

```
CRIT[09-06|10:22:54] error executing                          module=main cmd=infrakit err="invalid character ' ' in numeric literal" fn=main.main
invalid character ' ' in numeric literal
```

```yaml
- Plugin: group
  Properties:
    ID: cattle
    Properties:
      Allocation:
        Size: 5

      Instance:
        Plugin: instance-file
        Properties:
          Note: Instance properties verison 1.0

      Flavor:
        Plugin: flavor-vanilla
        Properties:
          Init:
            - docker pull nginx:alpine
            - docker run -d -p 80:80 nginx-alpine
          Tags:
            tier: web
            project: infrakit
          Attachments:
            - ID: attachid
              Type: attachtype
```
