### ISSUE TITLE
Vagrant provisioning too many machines

### ISSUE THREAD

**Issue by OverlyExcessive** [docker/infrakit#677]
I'm running a very basic configuration to provision 1 vagrant instance managed by Infrakit. This is resulting in a feedback loop where Infrakit is creating more and more machines until it locks up the computer completely, this is what I'm seeing from the group plugin logs:

```
{
    "V": "300",
    "descriptions": "[]",
    "groupID": "vagrant-centos7",
    "lvl": 4,
    "module": "plugin/group",
    "msg": "Found existing instances",
    "stack": "[github.com/docker/infrakit/pkg/plugin/group/quorum.go:91 github.com/docker/infrakit/pkg/plugin/group/quorum.go:67]",
    "t": "2017-09-07T10:44:05.525856287+02:00"
}
{
    "instance": "192.168.2.200",
    "lvl": 3,
    "module": "plugin/group",
    "msg": "Logical ID is missing, provisioning new instance",
    "stack": "[github.com/docker/infrakit/pkg/plugin/group/quorum.go:142 github.com/docker/infrakit/pkg/plugin/group/quorum.go:67]",
    "t": "2017-09-07T10:44:05.53083285+02:00"
}
```

And this is the group configuration:

```yaml
ID: vagrant-centos7
Properties:
  Allocation:
    LogicalIDs:
      - 192.168.2.200

  Instance:
    Plugin: instance-vagrant
    Properties:
      Note: Instance properties for vagrant vm (v0.1)
      Box: centos7
      Memory: 512
      CPUs: 1

  Flavor:
    Plugin: flavor-vanilla
    Properties:
      Init:
        - echo 'hello, world!' > /hello
      Tags:
        tier: docker-engines
        project: infrakit
```
