### ISSUE TITLE
Multiple LB ingress controller commits - LBs not called.

### ISSUE THREAD

**Issue by ericvn** [docker/infrakit#744]
I copied the existing example yml file into 2 new ymls and changed such that:

lb1 for a LB (uses simulator/lb1) which should be updated from the swarm,
lb2 for a LB (uses simulator/lb2) which has a hardcoded protocol.

If I only commit #1, and create and remove services, the protocols are added correctly to lb1.
If I commit #1 and #2, and create and remove a service, the protocols are not added to lb1.

If I commit #2 and then #1, things work fine.

lb1.yml:
```
kind: ingress
metadata:
  name: test1.com
  tags:
    project: testing
    user: chungers

# options block map to pkg/controller/ingress/types/Options
options:
  # SyncInterval is how often to sync changes between the services and the LB
  SyncInterval: 1s  # syntax is a string form of Go time.Duration

# properties block map to pkg/controller/ingress/types/Properties
properties:
  - Backends:
      Groups:
        - group/workers # This is a group at socket(group), groupID(workers).

    # This is the plugin name of the L4 plugin. When you run `infrakit plugin start ... simulator`
    # the default socket file name is 'simulator' and there's a default lb2 in the RPC object.
    L4Plugin: simulator/lb1

    # Plus all the services in Swarm that have --publish <frontend-port>:<container_port>
    RouteSources:
      swarm:
        Host: unix:///var/run/docker.sock
```

lb2.yml:
```
kind: ingress
metadata:
  name: test2.com
  tags:
    project: testing
    user: chungers

# options block map to pkg/controller/ingress/types/Options
options:
  # SyncInterval is how often to sync changes between the services and the LB
  SyncInterval: 1s  # syntax is a string form of Go time.Duration

# properties block map to pkg/controller/ingress/types/Properties
properties:
  - Backends:
      Groups:
        - group/workers # This is a group at socket(group), groupID(workers).

    # This is the plugin name of the L4 plugin. When you run `infrakit plugin start ... simulator`
    # the default socket file name is 'simulator' and there's a default lb2 in the RPC object.
    L4Plugin: simulator/lb2

    # Here we have a static route that is always present.
    Routes:
      - LoadBalancerPort: 80
        LoadBalancerProtocol: HTTP
        Port: 8080
        Protocol: HTTP
```

Another issue I am seeing (harder to recreate on a Mac) is that the backends for LB1 don't seem to be updated correctly as well.
