### ISSUE TITLE
Docs: Tutorial/README Contains Outdated Commands

### ISSUE THREAD

**Issue by aimeeu** [docker/infrakit#784]
infrakit/docs/tutorial/README.md  "A Quick Tour of InfraKit" CLI-> Working with Groups section:
'infrakit group/workers describe workers' should be 'infrakit group/workers describe'
'infrakit group/workers size workers' should be 'infrakit group/workers scale'

Possibly more that I'd like to fix as I go through the tutorial.

**Comment by roberthbailey** [comment]
I'm walking through https://github.com/docker/infrakit/tree/master/docs/tutorial and finding other outdated commands, e.g. `infrakit` doesn't show the plugins as top-level commands any longer, you need to run `infrakit local` to see them (and add local into subsequent commands to to describe / create simulated instances to get those to work).

**Comment by roberthbailey** [comment]
The section for provisioning a single instance worked well enough (after working though the issue described above) but the section for provisioning groups of instances didn't work at all for me (on a mac, if that makes a difference). 

Using the example specification

```yaml
#
#  A group of workers
#
#  Start up -- plugin start should include manager, vanilla, simulator, and group
#  Then commit
#
#  infrakit group controller commit -y docs/tutorial/group.yml
#
kind: group
metadata:
    name: workers
properties:
    Allocation:
      Size: 5
    Flavor:
      Plugin: vanilla
      Properties:
        Init:
          - sudo apt-get update -y
          - sudo apt-get install wget curl
          - wget -qO- https://get.docker.com | sh
        Tags:
          custom.tag1 : tutorial
          custom.tag2 : single-instance
          custom.tag3 : by-group

    Instance:
      Plugin: simulator/compute
      # This section here for the Instance plugin is the same as the example
      # for creating a single instance.  The Tags and Init sections are now
      # handled by the Flavor plugin
      Properties:
        apiProperty1 : value1
        apiProperty2 : value2
```
I didn't find a command that would allow me to commit it to a group controller. The commit commands all failed with a timeout. Running list commands also resulted in a timeout, whereas describe commands returned (an empty list) successfully.
